connector.name=clickhouse
connection-url=jdbc:clickhouse://ch-target:8123/default?compress=0&socket_timeout=300000
connection-user=default
connection-password=pass
clickhouse.map-string-as-varchar=true